# Generated by Django 4.2.7 on 2025-06-03 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='챕터명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '챕터',
                'verbose_name_plural': '챕터',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='레슨명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('youtube_url', models.URLField(blank=True, verbose_name='유튜브 URL')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='영상 길이')),
                ('share_token', models.CharField(blank=True, max_length=32, unique=True, verbose_name='공유 토큰')),
                ('is_public_shareable', models.BooleanField(default=False, verbose_name='공개 공유 가능')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='챕터')),
            ],
            options={
                'verbose_name': '레슨',
                'verbose_name_plural': '레슨',
                'ordering': ['chapter__course', 'chapter__order', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='강의명')),
                ('description', models.TextField(verbose_name='설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='썸네일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개여부')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='강의'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.PositiveIntegerField(help_text='동영상 재생 시간(초)', verbose_name='타임스탬프(초)')),
                ('content', models.TextField(verbose_name='노트 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson', verbose_name='레슨')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공유 노트',
                'verbose_name_plural': '공유 노트',
                'ordering': ['lesson', 'timestamp'],
                'indexes': [models.Index(fields=['lesson', 'timestamp'], name='courses_not_lesson__5bc6e4_idx'), models.Index(fields=['lesson', '-created_at'], name='courses_not_lesson__aa6dad_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order')},
        ),
    ]
