# Generated by Django 4.2.7 on 2025-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='공유 토큰'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_public_shareable',
            field=models.BooleanField(default=False, verbose_name='공개 공유 가능'),
        ),
    ] 