# Generated by Django 4.2.7 on 2025-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_lesson_share_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_public_shareable',
            field=models.BooleanField(default=True, verbose_name='공개 공유 가능'),
        ),
    ]
